---
title: Was ist digital history?
suppress-bibliography: true
editor: 
  markdown: 
    wrap: sentence
---

Über die Antwort zur Frage, was digital history ist oder umfasst, kann man ausgiebig diskutieren; als Teilgebiet der digital humanities, der digitalen Geisteswissenschaften, kann die folgende aktuelle und pragmatische Definition von Blaney et al. hilfreich sein:

> Digital humanities, in our view, is a question of approach: if you are actively and critically using digital tools to aid your work in researching, teaching or learning, you are probably doing digital humanities.
> We would encourage anyone to learn to program if they are interested in doing so, but we do not see it as a defining characteristic of work in digital humanities.
> [@blaney_doing_2021, S. 6]

Dabei umfassen "digital tools" eine große Bandbreite -- und es wird sich kaum eine:r finden, der:die Studium, Forschung oder Lehre völlig ohne die Nutzung digitaler Techniken betreibt.
Wir sind alle Historiker:innen im digitalen Zeitalter, und als solche müssen wir ohnehin neue Kompetenzen entwickeln.
Wir können uns aber zudem dafür entscheiden, für ein Forschungsprojekt Methoden und Techniken einzusetzen, die über die traditionellen Werkzeuge der Geschichtswissenschaften hinausgehen -- Analyse und Interpretation von Quellen durch deren genaue Lektüre, sogenanntes [*close reading*](https://de.wikipedia.org/wiki/Close_Reading) --, und uns durch den Computer unterstützen lassen.
Ob wir hierbei auf vorhandene Software zurückgreifen oder selbst Programme schreiben, um uns nicht nur als Historiker:innen im digitalen Zeitalter, sondern auch als digitale Historiker:innen zu verstehen, mögen manche als Glaubensfrage auffassen; eine inkludierende Haltung zu dieser Frage scheint mir dabei nur Vorteile zu haben.[Entgegen einer häufig zitierten Aussage von Emmanuel Le Roy Ladurie (\*1929), der Historiker von morgen werde Programmierer sein, oder er werde nicht sein: "L'historien de demain sera programmeur ou il ne sera pas." @le_roy_ladurie_fin_1968]

Für eine erste Idee dafür, wie man historische Fragestellungen mithilfe digitaler Methoden beantworten kann und wie unterschiedlich digital unterstützte Forschungsprojekte aussehen können, bietet sich unter anderem der Übersichtsartikel "[State of the Field: Digital History](https://onlinelibrary.wiley.com/doi/10.1111/1468-229X.12969)" von Romein et al. (2020) an.[@romein_state_2020] Eine anwachsende Liste an Beispielprojekten aus unterschiedlichen Epochen bzw.
Themenbereichen findet sich unter [Projekte und Ressourcen](02_forschung_lehre.qmd##Projekte und Ressourcen) in Kapitel 2.

Um eine Annäherung an die aktive, kritische und reflektierte Nutzung digitaler Methoden in Forschung und Lehre mit einem Fokus auf deren Anwendung in den Geschichtswissenschaften geht es im vorliegenden Guide.
Weiterführende Texte zur Frage, was digital history ist bzw.
umfasst, finden sich unter [Further Ressources](further_ressources.qmd##Was ist digital history?)
