---
title: "Through the Front Door"
lang: en
suppress-bibliography: true
editor: 
  markdown: 
    wrap: sentence
---

Imagine you would like to study the letters of Franz Marc to Herwarth Walden for a research project. 
You are mainly interested in what salutations Marc uses in his letters to Walden, in order to possibly draw inferences about the relationship between the two. 
How would you go about getting an overview? 
Would you use the download options of the website or read the letters online? 
What steps would you take to save the letters on your computer? 
Please note your answers to all questions in a document.

There are a number of paths you could take and none are better or worse, but some might be more efficient than others, meaning that you save time you can use for other things, be that in studying or at the swimming pool.

Whatever method you chose, continue with the following:\
1. Create an overview of all the salutations in the 45 letters by Franz Marc to Herwarth Walden. 
Which format you choose, analogue or digital, or which file type you use, is up to you.\
2. Take letter no 8 from Marc to Walden and divide it into its constitutive structural parts.\ 
Again it is your choice whether you print the letter and mark the elements with a pen or work on your computer.\ 
What you define as being a structural element is part of the exercise. (In a poem, possible elements could be title and verse)\
3. Take the same letter and mark all entities, such as persons, places etc. 
Create a spreadsheet (with Excel, Google Sheets, Open Office or suchlike), and enter the entities.

After you have done this, read “The Ten Commandments of Inputting Data” in chapter 3 of the book “Quantitative Methods in the Humanities”.[@lemercier_quantitative_2019, pp. 57--60] 
You will find the chapter in the ADAM-Workspace of your introductory course -- the whole thing is worth reading, but the “Ten Commandments” are enough to start with.
You can find a more practically focused online version  [here](https://quanthum.hypotheses.org/239) in the blog accompanying the book.

After reading the "Ten Commandments", would you do something different in step 3 of the exercise? 
Write down everything you would do differently, or any new insights, and bring your results to the scheduled meeting in the introductory course, be it in analogue or digital form.
