---
title: "Literature, Tools, Tutorials"
lang: en
format: html
editor: visual
---

## What is digital history? {#sec-digitalhistory-paper}

- Antenhofer, Christina, Kühberger, Christoph, Strohmeyer, Arno (Hrsg.): Digital Humanities in den Geschichtswissenschaften. Wien 2023.

- Brennan, Sheila A.: Digital History, in: The Inclusive Historian's Handbook, <https://inclusivehistorian.com/digital-history/>, 04.06.2019.

- Hohls, Rüdiger: Digital Humanities und digitale Geschichtswissenschaften, in: Busse, Laura u. a. (Hg.): Clio-Guide. Ein Handbuch zu digitalen Ressourcen für die Geschichtswissenschaften, Berlin 2018, pp. A.1-1--B.1-34. Online: <https://doi.org/10.18452/19244>.

- Romein, C. Annemieke u. a.: State of the Field: Digital History, in: History 105 (365), 04.2020, pp. 291---312. Online: <https://doi.org/10.1111/1468-229X.12969>.

- Winters, Jane: Digital History, in: Tamm, Marek; Burke, Peter (Hg.): Debating New Approaches to History, London 2019, pp. 277--300.

- Art. "Digital history", in: Wikipedia, 07.09.2022. Online: <https://en.wikipedia.org/w/index.php?title=Digital_history&oldid=1220662831>, Stand: 25.04.2024.

## Introductions and Guides

- Battershill, Claire; Ross, Shawna: Using Digital Humanities in the Classroom. A Practical Introduction for Teachers, Lecturers, and Students, London u.a. 2022.

- Blaney, Jonathan u. a.: Doing Digital History. A Beginner's Guide to Working with Text as Data, Manchester 2021.

- Cohen, Daniel J.; Rosenzweig, Roy: Digital History. A Guide to Gathering, Preserving, and Presenting the Past on the Web, Philadelphia 2006. Online: <https://chnm.gmu.edu/digitalhistory/>.

- Döring, Karoline u. a. (Hg.): Digital History. Konzepte, Methoden und Kritiken Digitaler Geschichtswissenschaft, Boston 2022, Online: <https://doi.org/10.1515/9783110757101>.

- Dougherty, Jack; Nawrotzki, Kristen (Hg.): Writing History in the Digital Age, 2013. Online: <https://doi.org/10.3998/dh.12230987.0001.001>.

- Graham, Shawn u. a.: Exploring Big Historical Data. The Historian's Macroscope, 2022. Online: <https://doi.org/10.1142/12435>.

- Lemercier, Claire; Zalc, Claire: Quantitative Methods in the Humanities. An Introduction, Charlottesville 2019.

- Peroni, Silvio: [The CTP Book](https://comp-think.github.io/). A book for teaching Computational Thinking and Programming skills to people with a background in the Humanities.

## Digital History Tools (free/open source) {#sec-digitaltoolsen}

### General

- Programming Historian: [Tutorials for different tools and methods for historical teaching and research](https://programminghistorian.org/)

### Data Analysis

- [Datasette](https://datasette.io/): interactive tool for data exploration and visualisation

- [Heurist](https://heuristnetwork.org/): web based research environment for data collection, exploration and visualisation 

- [Nodegoat](https://nodegoat.net/): web based research environment for data collection, exploration and visualisation

### Maps

- [Dariah GeoBrowser](https://de.dariah.eu/geobrowser): web based tool for the depiction of spatiotemporal data 

- [QGis](https://qgis.org/de/site/): software for creating, processing, depicting and analysing spatial information 

- [Map in Seconds](http://mapinseconds.com/): web based tool for creating maps (optimised for Chrome)

- [Palladio](http://hdlab.stanford.edu/palladio/): web based tool for visualising structural data, a.o. geodata 

### Network Analysis

- [Gephi](https://gephi.org/): programme for analysing and visualising graphs and networks  

- [Nodegoat](https://nodegoat.net/): web based research environment for data collection, exploration and visualisation, a.o. network analysis

- [Palladio](http://hdlab.stanford.edu/palladio/): web based tool for visualising structural data, a.o. network analysis

### Text/Corpus Analysis

- AntConc: [tool kit for corpus analysis](http://laurenceanthony.net/software.html)

- Lemmatisation: [collection of the FID Romanistik](https://fid-romanistik.de/forschungsdaten/suche-nach-forschungsdaten/fid-internetressourcen/tools/werkzeuge-fuer-die-lemmatisierung-von-texten)

- Natural Language Toolkit, package for Python for Tokenisaton, Lemmatisation etc.: [NLTK](https://www.nltk.org/)

- Tokenisation: [tutorial by fortext for NLTK](https://fortext.net/routinen/lerneinheiten/preprocessing-mit-nltk)

- Voyant-Tools: [xollection of tools for text analysis, browser based or standalone](https://voyant-tools.org)

### Storytelling

- [Omeka](https://omeka.org): web based platform for the curation of digital exhibitions, for exhibiting and publishing images/objects 

- [StoryLine JS](http://storyline.knightlab.com/): tool for creating interactive diagrams

- [StoryMap JS](https://storymap.knightlab.com): tool for creating interactive maps/images with various elements

- [Timeline JS](https://timeline.knightlab.com): tool for creating interactive timelines

### Visualisation

- Bostock, Michael; Heer, Jeffrey; Ogievetsky, Vadim: A Tour through the Visualization Zoo. A Survey of Powerful Visualization Techniques, from the Obvious to the Obscure, in: Queue 8, No. 5 (2010). Online: <https://queue.acm.org/detail.cfm?id=1805128>

- [Data Visualisation Catalogue](https://datavizcatalogue.com/search.html): a guide to choosing forms of visualisation

- [Datasette](https://datasette.io/): interactive tool for data exploration and visualisation

- FID Romanistik: [collection of tools for visualisation](https://fid-romanistik.de/forschungsdaten/suche-nach-forschungsdaten/fid-internetressourcen/tools/werkzeuge-fuer-die-visualisierung-von-daten)

- [Palladio](http://hdlab.stanford.edu/palladio/): web based tool for visualising structural data

- [RAWGraphs](https://www.rawgraphs.io/): tool for the visualisation of tabular data (.tsv, .csv, .dsv or .json-files)

## Digital Literacy, Digital Criticism

- Ekström, Andreas: The Moral Bias behind your Search Results, TED talk 7.12.2015 (9:18), Online: <https://www.youtube.com/watch?v=_vBggxCNNno>.

- Gibbs, Frederick W.: New Forms of History: Critiquing Data and Its Representations, in: The American Historian, February 2016. Online: <http://tah.oah.org/february-2016/new-forms-of-history-critiquing-data-and-its-representations/>.

- Tavani, Herman; Zimmer, Michael: Search Engines and Ethics, in: Edward N. Zalta (Hg.): The Stanford Encyclopedia of Philosophy (Fall 2020 Edition), Online: <https://plato.stanford.edu/archives/fall2020/entries/ethics-search/>, ch. 3.1.

## Programming Languages & Editors

- Python:
  - Althage, Melanie u. a.: Python für Historiker:innen. Ein anwendungsorientierter und interaktiver Einstieg, 20.07.2022, [Jupyter Book, (v1.0)](https://digital-history-berlin.github.io/Python-fuer-Historiker-innen/home.html)
  - Karsdorp, Folgert: [Python Programming for the Humanities. Interactive Tutorial and Introduction to Programming with Python for the Humanities.](http://www.karsdorp.io/python-course/)
  - Mattingly, William : [PythonHumanities.com. A Free Course for the Digital Humanities.](https://pythonhumanities.com/)
  - Editor e.g. [PyCharm](https://www.jetbrains.com/pycharm/)
- R:
  - Mullen, Lincoln A.: [Computational Historical Thinking With Applications in R](https://dh-r.lincolnmullen.com/)
  - Phillips, Nathaniel D.: [YaRrr! The Pirate's Guide to R.](https://bookdown.org/ndphillips/YaRrr/)
  - Wickham, Hadley; Grolemund, Garrett: [R for Data Science.](https://r4ds.had.co.nz/)
  - Editor e.g. [RStudio](https://posit.co/downloads/)
- Editors: [Anaconda](https://www.anaconda.com/); [Sublime Text](https://www.sublimetext.com/); [Visual Studio Code](https://code.visualstudio.com/)

## Regular Expressions

- Knox, Doug: Understanding Regular Expressions, Programming Historian 2 (2013), <https://doi.org/10.46430/phen0033>. (self-learning lesson)

- RegexOne: [Learn Regular Expressions with simple, interactive exercises.](https://regexone.com/) (interactive self-learning tutorial)

## Terminal/Command Line/Shell

- Dawson, Ted: Introduction to the Windows Command Line with PowerShell, Programming Historian 5 (2016), <https://doi.org/10.46430/phen0054>. (self-learning lesson)

- MIT Computer Science Department: [1-hour-lecture on the Shell](https://missing.csail.mit.edu/2020/course-shell/) (video)

- Milligan, Ian; Baker, James: Introduction to the Bash Command Line, Programming Historian 3 (2014), <https://doi.org/10.46430/phen0037> (self-learning lesson)

- datacamp course:[Introduction to Shell](https://app.datacamp.com/learn/courses/introduction-to-shell) (interactive self-learning lesson)

- Jeroen Janssens: [Data Science at the command line](https://datascienceatthecommandline.com/) (book)

## XML

- Latex Ninja Blog: [A shamelessly short intro to XML for DH beginners (includes TEI)](https://latex-ninja.com/2022/02/02/a-shamelessly-short-intro-to-xml-for-dh-beginners-includes-tei/) (blog post)
